#CODE1.0:
#use FROM to configure the base container image to build on
#see - https://docs.docker.com/engine/reference/builder/#from

#CODE1.1:
#use RUN to install the flask python library using the pip command
#see - https://docs.docker.com/engine/reference/builder/#run

#CODE1.2:
#use RUN to create an empty directory to host the python flask main.py application file
#see - https://docs.docker.com/engine/reference/builder/#run

#CODE1.3:
#use WORKDIR to change the current working directory
#see - https://docs.docker.com/engine/reference/builder/#workdir

#CODE1.4:
#use COPY to copy across the main.py file into the current working directory
#see - https://docs.docker.com/engine/reference/builder/#copy

#CODE1.5:
#use ENV to set the FLASK_APP environment variable - tells the flask runtime where to start
#see - https://docs.docker.com/engine/reference/builder/#env

#CODE1.6:
#use ENV to set the APP_NAME environment variable - ref and used in the main.py file 
#see - https://docs.docker.com/engine/reference/builder/#env

#CODE1.7:
#use the CMD to set the default execution for the container when launched
#see - https://docs.docker.com/engine/reference/builder/#cmd
